// SEOGRAM Cloud Fleet Publisher - Autonomous Multi-Blog Engine
// Compatible with Node 18+ (Linux, Windows, macOS, GitHub Actions)

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const CURL = process.platform === 'win32' ? 'curl.exe' : 'curl';

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://hiicvzmiwfwqkuhnongz.supabase.co';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaWN2em1pd2Z3cWt1aG5vbmd6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTY3MTQ2MSwiZXhwIjoyMTA1MjQ3NDYxfQ.lUrV3s8wPVGcpj-o1DHXLNyy44ALR_czEL_jqCrjuuM';

const BLOGFA_BLOG_ID = '33333333-3333-3333-3333-333333333333';
const ROZ_BLOG_ID = '44444444-4444-4444-4444-444444444444';
const BLOGFA_FORM_URL = 'https://blogfa.com/desktop/Post.aspx?action=new&t=71554240';

const STATUS_FILE = path.resolve(__dirname, '..', 'publish_status.json');
const ROZ_COOKIES = path.resolve(__dirname, 'roz_cookies.txt');
const BLOGFA_COOKIES = path.resolve(__dirname, 'blogfa_cookies.txt');

function initCookies() {
  if (!fs.existsSync(BLOGFA_COOKIES) || fs.statSync(BLOGFA_COOKIES).size < 50) {
    const rawBlogfa = `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_blogfa.com\tFALSE\t/\tFALSE\t0\t.AXB\tED2FA8200EF594FCFEE1782705C3904E4F3C71B81A1B93E3EB70B4FBF642230CADB225EB8908DECBA315ECDD74F87FC281649CD2439175531B0BABC1D11D45DF7B0B01131ECC2EEFB6DB5EF7E0D501D3AAF0F8AA34F5C36E7E4CCB048EAD1E7D4AE61FA4CEA489B449DBF144AA2461498CA1CDE2D5B849C07A1CD5F273C32699B674B69E
blogfa.com\tFALSE\t/\tFALSE\t0\tpubset\tar=1&tz=irn%2b210&ds=0&cmt=0&cats=1&tag=0&nu=1&bt=2YbYqNi2INmI2Kgg2Ygg2YfZiNi0INmF2LXZhtmI2LnbjA==
#HttpOnly_blogfa.com\tFALSE\t/\tFALSE\t0\tten\t71554240
`;
    fs.writeFileSync(BLOGFA_COOKIES, rawBlogfa, 'utf8');
    console.log('✓ Initialized Blogfa cookies.');
  }

  if (!fs.existsSync(ROZ_COOKIES) || fs.statSync(ROZ_COOKIES).size < 100) {
    const rawRoz = `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

www.rozblog.com\tFALSE\t/\tTRUE\t1790005170\tROZBLOG_SESSION\t65935a9b344823f4212ece914223d12b
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tBlogid\t800021
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tweblog\tooblog
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tuser\tooblog
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tpass\t79903bfe3a5ec6d7b81b92442776b91b
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tname\t%D8%A7%D8%B3%D8%AA%D9%88%D8%AF%DB%8C%D9%88%20%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C%20
`;
    fs.writeFileSync(ROZ_COOKIES, rawRoz, 'utf8');
    console.log('✓ Initialized Rozblog cookies.');
  }
}

function ensureRozblogLogin() {
  initCookies();
  let needsLogin = false;
  try {
    const check = execSync(`${CURL} -k -s -b "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 "https://www.rozblog.com/usercp.php"`, { encoding: 'utf8', timeout: 20000 });
    if (!check.includes('panel') && !check.includes('خروج') && !check.includes('new_post')) {
      needsLogin = true;
    }
  } catch (e) {
    needsLogin = true;
  }

  if (needsLogin) {
    console.log('Refreshing Rozblog session...');
    try {
      const html = execSync(`${CURL} -k -s -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 https://www.rozblog.com/login.php`, { encoding: 'utf8', timeout: 20000 });
      const m = html.match(/name="sec_code"[^>]*value="([^"]+)"/);
      const secCode = m ? m[1] : '';

      const cmd = `${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 20 -e "https://www.rozblog.com/login.php" -F "login_ddd=1" -F "sec_code=${secCode}" -F "rb_username=ooblog" -F "password=Kolsoom123456@" "https://www.rozblog.com/login.php?ajax=1"`;
      execSync(cmd, { encoding: 'utf8', timeout: 30000 });
      console.log('✓ Rozblog authentication renewed.');
    } catch (err) {
      console.error('Rozblog login attempt:', err.message);
    }
  }

  // Get active panel base URL
  try {
    const usercp = execSync(`${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 "https://www.rozblog.com/usercp.php"`, { encoding: 'utf8', timeout: 20000 });
    const match = usercp.match(/href="(\/panel\d+\/new_post)"/);
    if (match) {
      const panelToken = match[1].split('/')[1];
      return `https://www.rozblog.com/${panelToken}`;
    }
    const anyPanel = usercp.match(/\/panel\d+/);
    if (anyPanel) {
      return `https://www.rozblog.com${anyPanel[0]}`;
    }
  } catch (err) {
    console.error('Rozblog usercp error:', err.message);
  }
  return 'https://www.rozblog.com/panel284713228';
}

function getStatus() {
  if (fs.existsSync(STATUS_FILE)) {
    try {
      return JSON.parse(fs.readFileSync(STATUS_FILE, 'utf8'));
    } catch (e) {}
  }
  return {
    github: 1000,
    gitlab: 1000,
    blogfa_published: 64,
    blogfa_total: 1402,
    rozblog_published: 96,
    rozblog_total: 1002,
    last_updated: new Date().toISOString()
  };
}

function saveStatus(data) {
  fs.writeFileSync(STATUS_FILE, JSON.stringify(data, null, 2), 'utf8');
}

async function fetchSupabaseArticles(blogId, offset, limit) {
  const url = `${SUPABASE_URL}/rest/v1/articles?blog_id=eq.${blogId}&order=created_at.desc&offset=${offset}&limit=${limit}&select=id,title,slug,summary,content_markdown,content_html,tags`;
  
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(url, {
        headers: {
          'apikey': SERVICE_KEY,
          'Authorization': `Bearer ${SERVICE_KEY}`
        }
      });
      if (!res.ok) {
        throw new Error(`Supabase REST Error ${res.status}: ${await res.text()}`);
      }
      return await res.json();
    } catch (err) {
      if (attempt === 3) throw err;
      await new Promise(r => setTimeout(r, 2000));
    }
  }
}

function publishRozblogArticle(panelBase, article) {
  const newPostUrl = `${panelBase}/new_post`;
  let html;
  try {
    html = execSync(`${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 "${newPostUrl}"`, { encoding: 'utf8', timeout: 20000 });
  } catch (err) {
    return false;
  }

  if (html.includes('حداکثر ارسال مطلب روزانه')) {
    console.log('⚠️ [Rozblog] سقف مجاز ارسال روزانه رزبلاگ (۱۰۰ پست در روز) تکمیل شده است. ادامه مقالات فردا ارسال خواهد شد.');
    return 'DAILY_LIMIT';
  }

  const tokenMatch = html.match(/name="token_key"\s+value="([^"]+)"/);
  const bMatch = html.match(/name="b"\s+value="([^"]+)"/);
  const purlMatch = html.match(/name="purl_var"\s+value="([^"]+)"/);

  if (!tokenMatch || !bMatch) return false;

  const tokenKey = tokenMatch[1];
  const bVal = bMatch[1];
  const purlVar = purlMatch ? purlMatch[1] : '';

  const tmpFile = path.resolve(__dirname, `roz_tmp_${Date.now()}_${Math.random().toString(36).substring(7)}.tmp`);
  const content = article.content_html || article.content_markdown || article.summary || `<p>${article.title}</p>`;
  fs.writeFileSync(tmpFile, content, 'utf8');

  let tags = 'دیزاین,گرافیک,تایپوگرافی';
  if (Array.isArray(article.tags)) tags = article.tags.join(',');
  const title = (article.title || '').replace(/"/g, '\\"');

  try {
    const cmd = `${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 30 \
-e "${newPostUrl}" \
-F "post_6=1" \
-F "purl_var=${purlVar}" \
-F "post_bid=1" \
-F "mtitle=${title}" \
-F "mtex=<${tmpFile}" \
-F "mtex2=" \
-F "ptags=${tags}" \
-F "pcm=1" \
-F "status=1" \
-F "member=0" \
-F "idtA=1" \
-F "pdayA=28" \
-F "pmonthA=6" \
-F "pyearA=1405" \
-F "phourA=12" \
-F "pminuteA=30" \
-F "submit_post=1" \
-F "b=${bVal}" \
-F "token_key=${tokenKey}" \
"${newPostUrl}"`;

    const resp = execSync(cmd, { encoding: 'utf8', timeout: 35000 });
    const success = resp.includes('با موفقیت') || resp.includes('ثبت شد') || resp.includes('success') || resp.length > 20000;
    return success;
  } catch (err) {
    return false;
  } finally {
    if (fs.existsSync(tmpFile)) {
      try { fs.unlinkSync(tmpFile); } catch {}
    }
  }
}

function publishBlogfaArticle(article, index, globalCount = 70) {
  let html;
  try {
    html = execSync(`${CURL} -s -b "${BLOGFA_COOKIES}" -c "${BLOGFA_COOKIES}" -L --max-time 15 "${BLOGFA_FORM_URL}"`, { encoding: 'utf8', timeout: 20000 });
  } catch (err) {
    return false;
  }

  const vs = (html.match(/id="__VIEWSTATE" value="([^"]+)"/) || ['', ''])[1];
  const vsg = (html.match(/id="__VIEWSTATEGENERATOR" value="([^"]+)"/) || ['', ''])[1];
  const ev = (html.match(/id="__EVENTVALIDATION" value="([^"]+)"/) || ['', ''])[1];

  if (!vs || !ev) return false;

  const day = (html.match(/name="txtDay"[^>]*value="([^"]+)"/) || ['', '28'])[1];
  const month = (html.match(/name="txtMonth"[^>]*value="([^"]+)"/) || ['', '06'])[1];
  const year = (html.match(/name="txtYear"[^>]*value="([^"]+)"/) || ['', '1405'])[1];

  let content = article.summary || article.content_markdown || article.title;
  content = content.replace(/^#+\s*/gm, '').trim();

  // Distribute across past days with unique hour/min based on absolute post sequence
  const postSeq = globalCount + index;
  const pastDay = String(Math.max(1, 26 - (postSeq % 25))).padStart(2, '0');
  const pastHour = String((postSeq * 7 + 5) % 23).padStart(2, '0');
  const pastMin = String((postSeq * 17 + 13) % 58).padStart(2, '0');

  const baseParams = {
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__VIEWSTATE': vs,
    '__VIEWSTATEGENERATOR': vsg,
    '__EVENTVALIDATION': ev,
    'hasextended': 'false',
    'ismobile': 'false',
    'txtPostTitle': (article.title || '').replace(/[^\u0600-\u06FF\s0-9a-zA-Z\-_:؛،()]/g, ' ').replace(/\s+/g, ' ').trim().substring(0, 95),
    'txtPostContent': content,
    'txtPostExtended': '',
    'btnPublish': 'ثبت نوشته و انتشار',
    'txtTags': '',
    'cmbCommentType': '9',
    'txtDay': pastDay,
    'txtMonth': month,
    'txtYear': year,
    'txtMinute': pastMin,
    'txtHour': pastHour,
    'txtPostPW': ''
  };

  const variations = [
    { desc: 'past+nocat', params: {} },
    { desc: 'past+cat1', params: { 'chkCategories_1': '1' } },
    { desc: 'auto+cat', params: { 'chkAutomateTime': 'on', 'chkCategories_1': '1' } }
  ];

  for (const v of variations) {
    const p = new URLSearchParams();
    for (const [k, val] of Object.entries({ ...baseParams, ...v.params })) {
      p.append(k, val);
    }

    const tmp = path.resolve(__dirname, `blogfa_tmp_${Date.now()}_${Math.random().toString(36).substring(7)}.tmp`);
    fs.writeFileSync(tmp, p.toString(), 'utf8');

    try {
      const res = execSync(`${CURL} -s -b "${BLOGFA_COOKIES}" -c "${BLOGFA_COOKIES}" -e "${BLOGFA_FORM_URL}" -H "Content-Type: application/x-www-form-urlencoded" --data @${tmp} --max-time 20 "${BLOGFA_FORM_URL}"`, { encoding: 'utf8', timeout: 25000 });
      const ok = res.includes('موفقیت') || res.includes('نوشته ارسالی به ثبت رسید') || res.includes('بازسازی وبلاگ') || res.includes('Post.aspx?action=edit');
      if (ok) return true;
    } catch (e) {
    } finally {
      if (fs.existsSync(tmp)) {
        try { fs.unlinkSync(tmp); } catch {}
      }
    }
  }

  return false;
}

async function runPublisherCycle(batchSize = 15) {
  console.log(`\n======================================================`);
  console.log(`🚀 SEOGRAM Cloud Publisher Starting (Batch Size: ${batchSize})`);
  console.log(`   Time: ${new Date().toISOString()}`);
  console.log(`======================================================\n`);

  initCookies();
  const rozPanel = ensureRozblogLogin();
  const status = getStatus();

  console.log(`Current Status: Blogfa: ${status.blogfa_published}/${status.blogfa_total}, Rozblog: ${status.rozblog_published}/${status.rozblog_total}`);

  // 1. Rozblog Batch
  if (status.rozblog_published < 1000) {
    console.log(`\n--- [Rozblog] Fetching next batch of ${batchSize} articles ---`);
    try {
      const rozArticles = await fetchSupabaseArticles(ROZ_BLOG_ID, status.rozblog_published, batchSize);
      console.log(`Fetched ${rozArticles.length} articles from Supabase.`);

      let rozSuccessCount = 0;
      for (let i = 0; i < rozArticles.length; i++) {
        const ok = publishRozblogArticle(rozPanel, rozArticles[i]);
        if (ok === 'DAILY_LIMIT') {
          break;
        }
        if (ok) {
          status.rozblog_published += 1;
          rozSuccessCount++;
          console.log(`✓ [Rozblog] (${status.rozblog_published}/1000) ${rozArticles[i].title.substring(0, 50)}...`);
        } else {
          console.log(`✗ [Rozblog] Failed: ${rozArticles[i].title.substring(0, 50)}...`);
        }
        await new Promise(r => setTimeout(r, 1200));
      }
      console.log(`Rozblog batch complete: +${rozSuccessCount} published.`);
    } catch (err) {
      console.error('Error in Rozblog cycle:', err.message);
    }
  } else {
    console.log('✓ Rozblog target of 1,000 articles already achieved!');
  }

  // 2. Blogfa Batch
  if (status.blogfa_published < 1000) {
    console.log(`\n--- [Blogfa] Fetching next batch of ${batchSize} articles ---`);
    try {
      const blogfaArticles = await fetchSupabaseArticles(BLOGFA_BLOG_ID, status.blogfa_published, batchSize);
      console.log(`Fetched ${blogfaArticles.length} articles from Supabase.`);

      let blogfaSuccessCount = 0;
      for (let i = 0; i < blogfaArticles.length; i++) {
        const ok = publishBlogfaArticle(blogfaArticles[i], i, status.blogfa_published);
        if (ok) {
          status.blogfa_published += 1;
          blogfaSuccessCount++;
          console.log(`✓ [Blogfa] (${status.blogfa_published}/1000) ${blogfaArticles[i].title.substring(0, 50)}...`);
        } else {
          console.log(`✗ [Blogfa] Failed: ${blogfaArticles[i].title.substring(0, 50)}...`);
        }
        await new Promise(r => setTimeout(r, 1200));
      }
      console.log(`Blogfa batch complete: +${blogfaSuccessCount} published.`);

      // Regenerate Blogfa cache
      try {
        execSync(`${CURL} -s -b "${BLOGFA_COOKIES}" -c "${BLOGFA_COOKIES}" --max-time 15 "https://blogfa.com/desktop/refreshblog.ashx?r=${Date.now()}"`, { timeout: 20000 });
        console.log('✓ Blogfa static cache refreshed.');
      } catch (e) {}
    } catch (err) {
      console.error('Error in Blogfa cycle:', err.message);
    }
  } else {
    console.log('✓ Blogfa target of 1,000 articles already achieved!');
  }

  status.last_updated = new Date().toISOString();
  saveStatus(status);

  console.log(`\n======================================================`);
  console.log(`🏁 Cycle Complete. Updated Status:`);
  console.log(JSON.stringify(status, null, 2));
  console.log(`======================================================\n`);
}

if (require.main === module) {
  const batch = parseInt(process.argv[2], 10) || 15;
  runPublisherCycle(batch).catch(err => {
    console.error('Fatal Publisher Error:', err);
    process.exit(1);
  });
}

module.exports = { runPublisherCycle };
