// SEOGRAM Cloud Fleet Publisher - Autonomous Multi-Blog Engine
// Compatible with Node 18+ (Linux, Windows, macOS, GitHub Actions)

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const siteGenerator = require('./site_generator');
const { generate1000TechArticles } = require('./data_tech_topics');
const { generate1000DesignArticles } = require('./data_design_topics');

const CURL = process.platform === 'win32' ? 'curl.exe' : 'curl';

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://hiicvzmiwfwqkuhnongz.supabase.co';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaWN2em1pd2Z3cWt1aG5vbmd6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTY3MTQ2MSwiZXhwIjoyMTA1MjQ3NDYxfQ.lUrV3s8wPVGcpj-o1DHXLNyy44ALR_czEL_jqCrjuuM';

const BLOGFA_BLOG_ID = '33333333-3333-3333-3333-333333333333';
const ROZ_BLOG_ID = '44444444-4444-4444-4444-444444444444';
const BLOGFA_FORM_URL = 'https://blogfa.com/desktop/Post.aspx?action=new&t=71554240';

const GITLAB_TOKEN = process.env.GITLAB_TOKEN || 'glpat-McdMSexdGhOtBTjY44TUgmM6MQpvOjEKdTpwY2FnZQ8.01.171xwz569';
const GITLAB_PROJECT_ID = process.env.GITLAB_PROJECT_ID || '86641701';

const STATUS_FILE = path.resolve(__dirname, '..', 'publish_status.json');
const ROZ_COOKIES = path.resolve(__dirname, 'roz_cookies.txt');
const BLOGFA_COOKIES = path.resolve(__dirname, 'blogfa_cookies.txt');

function initCookies() {
  if (!fs.existsSync(BLOGFA_COOKIES) || fs.statSync(BLOGFA_COOKIES).size < 50) {
    const rawBlogfa = `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_blogfa.com\tFALSE\t/\tFALSE\t0\t.AXB\tED2FA8200EF594FCFEE1782705C3904E4F3C71B81A1B93E3EB70B4FBF642230CADB225EB8908DECBA315ECDD74F87FC281649CD2439175531B0BABC1D11D45DF7B0B01131ECC2EEFB6DB5EF7E0D501D3AAF0F8AA34F5C36E7E4CCB048EAD1E7D4AE61FA4CEA489B449DBF144AA2461498CA1CDE2D5B849C07A1CD5F273C32699B674B69E
blogfa.com\tFALSE\t/\tFALSE\t0\tpubset\tar=1&tz=irn%2b210&ds=0&cmt=0&cats=1&tag=0&nu=1&bt=2YbYqNi2INmI2Kgg2Ygg2YfZiNi0INmF2LXZhtmI2LnbjA==
#HttpOnly_blogfa.com\tFALSE\t/\tFALSE\t0\tten\t71554240
`;
    fs.writeFileSync(BLOGFA_COOKIES, rawBlogfa, 'utf8');
    console.log('✓ Initialized Blogfa cookies.');
  }

  if (!fs.existsSync(ROZ_COOKIES) || fs.statSync(ROZ_COOKIES).size < 100) {
    const rawRoz = `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

www.rozblog.com\tFALSE\t/\tTRUE\t1790005170\tROZBLOG_SESSION\t65935a9b344823f4212ece914223d12b
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tBlogid\t800021
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tweblog\tooblog
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tuser\tooblog
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tpass\t79903bfe3a5ec6d7b81b92442776b91b
www.rozblog.com\tFALSE\t/\tTRUE\t1792424373\tname\t%D8%A7%D8%B3%D8%AA%D9%88%D8%AF%DB%8C%D9%88%20%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C%20
`;
    fs.writeFileSync(ROZ_COOKIES, rawRoz, 'utf8');
    console.log('✓ Initialized Rozblog cookies.');
  }
}

function ensureRozblogLogin() {
  initCookies();
  let needsLogin = false;
  try {
    const check = execSync(`${CURL} -k -s -b "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 "https://www.rozblog.com/usercp.php"`, { encoding: 'utf8', timeout: 20000 });
    if (!check.includes('panel') && !check.includes('خروج') && !check.includes('new_post')) {
      needsLogin = true;
    }
  } catch (e) {
    needsLogin = true;
  }

  if (needsLogin) {
    console.log('Refreshing Rozblog session...');
    try {
      const html = execSync(`${CURL} -k -s -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 https://www.rozblog.com/login.php`, { encoding: 'utf8', timeout: 20000 });
      const m = html.match(/name="sec_code"[^>]*value="([^"]+)"/);
      const secCode = m ? m[1] : '';

      const cmd = `${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 20 -e "https://www.rozblog.com/login.php" -F "login_ddd=1" -F "sec_code=${secCode}" -F "rb_username=ooblog" -F "password=Kolsoom123456@" "https://www.rozblog.com/login.php?ajax=1"`;
      execSync(cmd, { encoding: 'utf8', timeout: 30000 });
      console.log('✓ Rozblog authentication renewed.');
    } catch (err) {
      console.error('Rozblog login attempt:', err.message);
    }
  }

  // Get active panel base URL
  try {
    const usercp = execSync(`${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 "https://www.rozblog.com/usercp.php"`, { encoding: 'utf8', timeout: 20000 });
    const match = usercp.match(/href="(\/panel\d+\/new_post)"/);
    if (match) {
      const panelToken = match[1].split('/')[1];
      return `https://www.rozblog.com/${panelToken}`;
    }
    const anyPanel = usercp.match(/\/panel\d+/);
    if (anyPanel) {
      return `https://www.rozblog.com${anyPanel[0]}`;
    }
  } catch (err) {
    console.error('Rozblog usercp error:', err.message);
  }
  return 'https://www.rozblog.com/panel284713228';
}

function getStatus() {
  if (fs.existsSync(STATUS_FILE)) {
    try {
      return JSON.parse(fs.readFileSync(STATUS_FILE, 'utf8'));
    } catch (e) {}
  }
  return {
    github: 1000,
    gitlab: 1000,
    github_last_drip: null,
    gitlab_last_drip: null,
    blogfa_published: 70,
    blogfa_total: 1402,
    rozblog_published: 126,
    rozblog_total: 1002,
    last_updated: new Date().toISOString()
  };
}

function saveStatus(data) {
  fs.writeFileSync(STATUS_FILE, JSON.stringify(data, null, 2), 'utf8');
}

async function fetchSupabaseArticles(blogId, offset, limit) {
  const url = `${SUPABASE_URL}/rest/v1/articles?blog_id=eq.${blogId}&order=created_at.desc&offset=${offset}&limit=${limit}&select=id,title,slug,summary,content_markdown,content_html,tags`;
  
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(url, {
        headers: {
          'apikey': SERVICE_KEY,
          'Authorization': `Bearer ${SERVICE_KEY}`
        }
      });
      if (!res.ok) {
        throw new Error(`Supabase REST Error ${res.status}: ${await res.text()}`);
      }
      return await res.json();
    } catch (err) {
      if (attempt === 3) throw err;
      await new Promise(r => setTimeout(r, 2000));
    }
  }
}

// --------------------------------------------------------------------------
// 1. GITHUB PAGES CONTINUOUS DRIP PUBLISHER (Tech & AI Magazine)
// --------------------------------------------------------------------------
function dripGitHubArticle(status) {
  const now = Date.now();
  const lastDrip = status.github_last_drip ? new Date(status.github_last_drip).getTime() : 0;
  const dripIntervalMs = 2 * 60 * 60 * 1000; // Natural 2-hour cadence (12 posts/day)

  if (lastDrip && (now - lastDrip < dripIntervalMs)) {
    const remMins = Math.round((dripIntervalMs - (now - lastDrip)) / 60000);
    console.log(`⏳ [GitHub Drip] Next live article scheduled in ~${remMins} minutes.`);
    return false;
  }

  console.log('\n--- 🚀 [GitHub Pages Drip] Publishing fresh live editorial article ---');
  const ghAuthors = [
    { name: 'امیرحسین پارسا' },
    { name: 'ندا شریفی' },
    { name: 'مهرداد ابراهیمی' },
    { name: 'سهراب کریمی' },
    { name: 'پروانه خسروی' }
  ];

  const currentCount = status.github || 1000;
  const nextIdx = currentCount + 1;
  const allTech = generate1000TechArticles(ghAuthors, []);
  const baseArt = allTech[(nextIdx - 1) % allTech.length];

  const todayIso = new Date().toISOString();
  const todayYmd = todayIso.split('T')[0];
  const slug = `${baseArt.slug}-drip-${nextIdx}`;

  // Image selection
  const ghRoot = path.resolve(__dirname, '..');
  const imgDir = path.join(ghRoot, 'assets', 'images');
  let imgName = 'tech-editorial-1.webp';
  if (fs.existsSync(imgDir)) {
    const imgs = fs.readdirSync(imgDir).filter(f => f.endsWith('.webp') && !f.includes('banner'));
    if (imgs.length > 0) {
      imgName = imgs[nextIdx % imgs.length];
    }
  }

  const newArticle = {
    ...baseArt,
    slug: slug,
    featured_image_url: `/assets/images/${imgName}`,
    featured_image_alt: baseArt.title,
    published_at: todayIso,
    created_at: todayIso
  };

  const blog = {
    title: 'نبض فناوری و هوش مصنوعی',
    description: 'پایگاه تخصصی رویدادها و اخبار فناوری‌های نوین و مدل‌های زبانی',
    target_url: 'https://pouriazizo-cmyk.github.io/tech-ai-pulse'
  };

  // 1. Write HTML with JSON-LD Schema
  const postHtml = siteGenerator.generateTechArticle(blog, newArticle, [], allTech.slice(0, 3));
  const postsDir = path.join(ghRoot, 'posts');
  if (!fs.existsSync(postsDir)) fs.mkdirSync(postsDir, { recursive: true });
  fs.writeFileSync(path.join(postsDir, `${slug}.html`), postHtml, 'utf8');

  // 2. Prepend article card to index.html
  const indexPath = path.join(ghRoot, 'index.html');
  if (fs.existsSync(indexPath)) {
    let indexHtml = fs.readFileSync(indexPath, 'utf8');
    const cardHtml = `
            <article class="article-card bg-white rounded-3xl overflow-hidden shadow-sm border border-slate-200/80 hover:shadow-md transition flex flex-col justify-between group">
              <div>
                <a href="posts/${slug}.html" class="block aspect-[16/9] overflow-hidden bg-slate-100 relative">
                  <img src="assets/images/${imgName}" alt="${newArticle.title}" loading="lazy" class="w-full h-full object-cover group-hover:scale-105 transition duration-300">
                  <span class="absolute top-3 right-3 bg-white/90 backdrop-blur text-xs font-bold px-2 py-0.5 rounded-full text-slate-700 shadow-sm">${newArticle.reading_time_minutes || 4} دقیقه</span>
                </a>
                <div class="p-6">
                  <div class="flex items-center gap-2 text-xs text-slate-500 mb-2">
                    <span class="font-bold text-sky-600">${newArticle.author_name}</span>
                    <span>•</span>
                    <span>هم‌اکنون</span>
                  </div>
                  <h3 class="text-base font-bold text-slate-900 group-hover:text-sky-600 transition leading-snug mb-2">
                    <a href="posts/${slug}.html">${newArticle.title}</a>
                  </h3>
                  <p class="text-xs text-slate-600 line-clamp-3 leading-relaxed">${newArticle.summary || newArticle.meta_description || ''}</p>
                </div>
              </div>
              <div class="px-6 pb-6 pt-0 flex items-center justify-between text-xs font-medium text-slate-500">
                <div class="flex flex-wrap gap-1">
                  ${(newArticle.tags || []).slice(0, 2).map(t => `<span class="bg-slate-100 text-slate-600 px-2 py-0.5 rounded-md text-[11px]"># ${t}</span>`).join('')}
                </div>
                <a href="posts/${slug}.html" class="text-sky-600 font-bold hover:underline">ادامه مطلب ←</a>
              </div>
            </article>`;

    if (indexHtml.includes('<div id="articles-grid" class="grid grid-cols-1 sm:grid-cols-2 gap-6">')) {
      indexHtml = indexHtml.replace('<div id="articles-grid" class="grid grid-cols-1 sm:grid-cols-2 gap-6">', `<div id="articles-grid" class="grid grid-cols-1 sm:grid-cols-2 gap-6">\n${cardHtml}`);
      fs.writeFileSync(indexPath, indexHtml, 'utf8');
    }
  }

  // 3. Update sitemap.xml
  const sitemapPath = path.join(ghRoot, 'sitemap.xml');
  if (fs.existsSync(sitemapPath)) {
    let sitemap = fs.readFileSync(sitemapPath, 'utf8');
    const newEntry = `  <url>\n    <loc>${blog.target_url}/posts/${slug}.html</loc>\n    <lastmod>${todayYmd}</lastmod>\n    <changefreq>daily</changefreq>\n    <priority>0.8</priority>\n  </url>\n</urlset>`;
    sitemap = sitemap.replace('</urlset>', newEntry);
    fs.writeFileSync(sitemapPath, sitemap, 'utf8');
  }

  // 4. Update rss.xml
  const rssPath = path.join(ghRoot, 'rss.xml');
  if (fs.existsSync(rssPath)) {
    let rss = fs.readFileSync(rssPath, 'utf8');
    const itemXml = `    <item>\n      <title>${newArticle.title.replace(/&/g, '&amp;')}</title>\n      <link>${blog.target_url}/posts/${slug}.html</link>\n      <guid isPermaLink="true">${blog.target_url}/posts/${slug}.html</guid>\n      <pubDate>${new Date().toUTCString()}</pubDate>\n      <description>${(newArticle.summary || newArticle.title).replace(/&/g, '&amp;')}</description>\n      <author>${newArticle.author_name}</author>\n    </item>\n  </channel>`;
    rss = rss.replace('  </channel>', itemXml);
    fs.writeFileSync(rssPath, rss, 'utf8');
  }

  // 5. Ping Google Sitemap Endpoint
  try {
    execSync(`${CURL} -s --max-time 10 "https://www.google.com/ping?sitemap=${encodeURIComponent(blog.target_url + '/sitemap.xml')}"`);
    console.log('✓ Google Search Console pinged for GitHub sitemap update.');
  } catch (e) {}

  status.github = nextIdx;
  status.github_last_drip = todayIso;
  console.log(`✓ [GitHub Drip] Article #${nextIdx} published successfully!`);
  return true;
}

// --------------------------------------------------------------------------
// 2. GITLAB PAGES CONTINUOUS DRIP PUBLISHER (Design & Typography Journal)
// --------------------------------------------------------------------------
async function dripGitLabArticle(status) {
  const now = Date.now();
  const lastDrip = status.gitlab_last_drip ? new Date(status.gitlab_last_drip).getTime() : 0;
  const dripIntervalMs = 2 * 60 * 60 * 1000; // Natural 2-hour cadence

  if (lastDrip && (now - lastDrip < dripIntervalMs)) {
    const remMins = Math.round((dripIntervalMs - (now - lastDrip)) / 60000);
    console.log(`⏳ [GitLab Drip] Next live article scheduled in ~${remMins} minutes.`);
    return false;
  }

  console.log('\n--- 🚀 [GitLab Pages Drip] Publishing fresh live design editorial ---');
  const glAuthors = [
    { name: 'فرهاد طاهری' },
    { name: 'سارا معتمد' },
    { name: 'رامتین دادگر' },
    { name: 'نگار خردمند' },
    { name: 'کاوه اردلان' }
  ];

  const currentCount = status.gitlab || 1000;
  const nextIdx = currentCount + 1;
  const allDesign = generate1000DesignArticles(glAuthors, []);
  const baseArt = allDesign[(nextIdx - 1) % allDesign.length];

  const todayIso = new Date().toISOString();
  const todayYmd = todayIso.split('T')[0];
  const slug = `${baseArt.slug}-drip-${nextIdx}`;

  const imgName = `design-editorial-${(nextIdx % 10) + 1}.webp`;

  const newArticle = {
    ...baseArt,
    slug: slug,
    featured_image_url: `/assets/images/${imgName}`,
    featured_image_alt: baseArt.title,
    published_at: todayIso,
    created_at: todayIso
  };

  const blog = {
    title: 'استودیو دیزاین، تایپوگرافی و تصویرسازی هوش مصنوعی',
    description: 'ژورنال تخصصی دیزاین، تایپوگرافی، فونت و تصویرسازی هوش مصنوعی',
    target_url: 'https://design-font-lab-011e29.gitlab.io'
  };

  const postHtml = siteGenerator.generateDesignArticle(blog, newArticle, [], allDesign.slice(0, 3));

  // Push to GitLab via REST API Commits endpoint
  try {
    const commitPayload = {
      branch: 'main',
      commit_message: `feat(content): publish live editorial ${newArticle.title.substring(0, 45)} [skip ci]`,
      actions: [
        {
          action: 'create',
          file_path: `posts/${slug}.html`,
          content: postHtml
        }
      ]
    };

    const res = await fetch(`https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/repository/commits`, {
      method: 'POST',
      headers: {
        'PRIVATE-TOKEN': GITLAB_TOKEN,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(commitPayload)
    });

    if (res.ok) {
      status.gitlab = nextIdx;
      status.gitlab_last_drip = todayIso;
      console.log(`✓ [GitLab Drip] Article #${nextIdx} committed to GitLab Pages via REST API!`);

      // Ping Google
      try {
        execSync(`${CURL} -s --max-time 10 "https://www.google.com/ping?sitemap=${encodeURIComponent(blog.target_url + '/sitemap.xml')}"`);
        console.log('✓ Google Search Console pinged for GitLab sitemap update.');
      } catch (e) {}

      return true;
    } else {
      const txt = await res.text();
      console.warn(`GitLab commit error status ${res.status}: ${txt}`);
    }
  } catch (err) {
    console.warn('GitLab drip network exception:', err.message);
  }
  return false;
}

// --------------------------------------------------------------------------
// 3. ROZBLOG BATCH PUBLISHER
// --------------------------------------------------------------------------
function publishRozblogArticle(panelBase, article) {
  const newPostUrl = `${panelBase}/new_post`;
  let html;
  try {
    html = execSync(`${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 15 "${newPostUrl}"`, { encoding: 'utf8', timeout: 20000 });
  } catch (err) {
    return false;
  }

  if (html.includes('حداکثر ارسال مطلب روزانه')) {
    console.log('⚠️ [Rozblog] سقف مجاز ارسال روزانه رزبلاگ (۱۰۰ پست در روز) تکمیل شده است. ادامه مقالات فردا ارسال خواهد شد.');
    return 'DAILY_LIMIT';
  }

  const tokenMatch = html.match(/name="token_key"\s+value="([^"]+)"/);
  const bMatch = html.match(/name="b"\s+value="([^"]+)"/);
  const purlMatch = html.match(/name="purl_var"\s+value="([^"]+)"/);

  if (!tokenMatch || !bMatch) return false;

  const tokenKey = tokenMatch[1];
  const bVal = bMatch[1];
  const purlVar = purlMatch ? purlMatch[1] : '';

  const tmpFile = path.resolve(__dirname, `roz_tmp_${Date.now()}_${Math.random().toString(36).substring(7)}.tmp`);
  const content = article.content_html || article.content_markdown || article.summary || `<p>${article.title}</p>`;
  fs.writeFileSync(tmpFile, content, 'utf8');

  let tags = 'دیزاین,گرافیک,تایپوگرافی';
  if (Array.isArray(article.tags)) tags = article.tags.join(',');
  const title = (article.title || '').replace(/"/g, '\\"');

  try {
    const cmd = `${CURL} -k -s -b "${ROZ_COOKIES}" -c "${ROZ_COOKIES}" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --max-time 30 \
-e "${newPostUrl}" \
-F "post_6=1" \
-F "purl_var=${purlVar}" \
-F "post_bid=1" \
-F "mtitle=${title}" \
-F "mtex=<${tmpFile}" \
-F "mtex2=" \
-F "ptags=${tags}" \
-F "pcm=1" \
-F "status=1" \
-F "member=0" \
-F "idtA=1" \
-F "pdayA=28" \
-F "pmonthA=6" \
-F "pyearA=1405" \
-F "phourA=12" \
-F "pminuteA=30" \
-F "submit_post=1" \
-F "b=${bVal}" \
-F "token_key=${tokenKey}" \
"${newPostUrl}"`;

    const resp = execSync(cmd, { encoding: 'utf8', timeout: 35000 });
    const success = resp.includes('با موفقیت') || resp.includes('ثبت شد') || resp.includes('success') || resp.length > 20000;
    return success;
  } catch (err) {
    return false;
  } finally {
    if (fs.existsSync(tmpFile)) {
      try { fs.unlinkSync(tmpFile); } catch {}
    }
  }
}

// --------------------------------------------------------------------------
// 4. BLOGFA BATCH PUBLISHER
// --------------------------------------------------------------------------
function publishBlogfaArticle(article, index, globalCount = 70) {
  let html;
  try {
    html = execSync(`${CURL} -s -b "${BLOGFA_COOKIES}" -c "${BLOGFA_COOKIES}" -L --max-time 15 "${BLOGFA_FORM_URL}"`, { encoding: 'utf8', timeout: 20000 });
  } catch (err) {
    return false;
  }

  const vs = (html.match(/id="__VIEWSTATE" value="([^"]+)"/) || ['', ''])[1];
  const vsg = (html.match(/id="__VIEWSTATEGENERATOR" value="([^"]+)"/) || ['', ''])[1];
  const ev = (html.match(/id="__EVENTVALIDATION" value="([^"]+)"/) || ['', ''])[1];

  if (!vs || !ev) return false;

  const day = (html.match(/name="txtDay"[^>]*value="([^"]+)"/) || ['', '28'])[1];
  const month = (html.match(/name="txtMonth"[^>]*value="([^"]+)"/) || ['', '06'])[1];
  const year = (html.match(/name="txtYear"[^>]*value="([^"]+)"/) || ['', '1405'])[1];

  let content = article.summary || article.content_markdown || article.title;
  content = content.replace(/^#+\s*/gm, '').trim();

  // Distribute across past days with unique hour/min based on absolute post sequence
  const postSeq = globalCount + index;
  const pastDay = String(Math.max(1, 26 - (postSeq % 25))).padStart(2, '0');
  const pastHour = String((postSeq * 7 + 5) % 23).padStart(2, '0');
  const pastMin = String((postSeq * 17 + 13) % 58).padStart(2, '0');

  const baseParams = {
    '__EVENTTARGET': '',
    '__EVENTARGUMENT': '',
    '__VIEWSTATE': vs,
    '__VIEWSTATEGENERATOR': vsg,
    '__EVENTVALIDATION': ev,
    'hasextended': 'false',
    'ismobile': 'false',
    'txtPostTitle': (article.title || '').replace(/[^\u0600-\u06FF\s0-9a-zA-Z\-_:؛،()]/g, ' ').replace(/\s+/g, ' ').trim().substring(0, 95),
    'txtPostContent': content,
    'txtPostExtended': '',
    'btnPublish': 'ثبت نوشته و انتشار',
    'txtTags': '',
    'cmbCommentType': '9',
    'txtDay': pastDay,
    'txtMonth': month,
    'txtYear': year,
    'txtMinute': pastMin,
    'txtHour': pastHour,
    'txtPostPW': ''
  };

  const variations = [
    { desc: 'past+nocat', params: {} },
    { desc: 'past+cat1', params: { 'chkCategories_1': '1' } },
    { desc: 'auto+cat', params: { 'chkAutomateTime': 'on', 'chkCategories_1': '1' } }
  ];

  for (const v of variations) {
    const p = new URLSearchParams();
    for (const [k, val] of Object.entries({ ...baseParams, ...v.params })) {
      p.append(k, val);
    }

    const tmp = path.resolve(__dirname, `blogfa_tmp_${Date.now()}_${Math.random().toString(36).substring(7)}.tmp`);
    fs.writeFileSync(tmp, p.toString(), 'utf8');

    try {
      const res = execSync(`${CURL} -s -b "${BLOGFA_COOKIES}" -c "${BLOGFA_COOKIES}" -e "${BLOGFA_FORM_URL}" -H "Content-Type: application/x-www-form-urlencoded" --data @${tmp} --max-time 20 "${BLOGFA_FORM_URL}"`, { encoding: 'utf8', timeout: 25000 });
      const ok = res.includes('موفقیت') || res.includes('نوشته ارسالی به ثبت رسید') || res.includes('بازسازی وبلاگ') || res.includes('Post.aspx?action=edit');
      if (ok) return true;
    } catch (e) {
    } finally {
      if (fs.existsSync(tmp)) {
        try { fs.unlinkSync(tmp); } catch {}
      }
    }
  }

  return false;
}

// --------------------------------------------------------------------------
// 5. MASTER CYCLE EXECUTION
// --------------------------------------------------------------------------
async function runPublisherCycle(batchSize = 15) {
  console.log(`\n======================================================`);
  console.log(`🚀 SEOGRAM Cloud Publisher Starting (Batch Size: ${batchSize})`);
  console.log(`   Time: ${new Date().toISOString()}`);
  console.log(`======================================================\n`);

  initCookies();
  const rozPanel = ensureRozblogLogin();
  const status = getStatus();

  console.log(`Current Status:`);
  console.log(`  • GitHub:  ${status.github || 1000} (Last drip: ${status.github_last_drip || 'Never'})`);
  console.log(`  • GitLab:  ${status.gitlab || 1000} (Last drip: ${status.gitlab_last_drip || 'Never'})`);
  console.log(`  • Blogfa:  ${status.blogfa_published}/${status.blogfa_total}`);
  console.log(`  • Rozblog: ${status.rozblog_published}/${status.rozblog_total}`);

  // 1. GitHub Pages Drip (Every 2 Hours)
  try {
    dripGitHubArticle(status);
  } catch (err) {
    console.error('GitHub drip error:', err.message);
  }

  // 2. GitLab Pages Drip (Every 2 Hours)
  try {
    await dripGitLabArticle(status);
  } catch (err) {
    console.error('GitLab drip error:', err.message);
  }

  // 3. Rozblog Batch
  if (status.rozblog_published < 1000) {
    console.log(`\n--- [Rozblog] Fetching next batch of ${batchSize} articles ---`);
    try {
      const rozArticles = await fetchSupabaseArticles(ROZ_BLOG_ID, status.rozblog_published, batchSize);
      console.log(`Fetched ${rozArticles.length} articles from Supabase.`);

      let rozSuccessCount = 0;
      for (let i = 0; i < rozArticles.length; i++) {
        const ok = publishRozblogArticle(rozPanel, rozArticles[i]);
        if (ok === 'DAILY_LIMIT') {
          break;
        }
        if (ok) {
          status.rozblog_published += 1;
          rozSuccessCount++;
          console.log(`✓ [Rozblog] (${status.rozblog_published}/1000) ${rozArticles[i].title.substring(0, 50)}...`);
        } else {
          console.log(`✗ [Rozblog] Failed: ${rozArticles[i].title.substring(0, 50)}...`);
        }
        await new Promise(r => setTimeout(r, 1200));
      }
      console.log(`Rozblog batch complete: +${rozSuccessCount} published.`);
    } catch (err) {
      console.error('Error in Rozblog cycle:', err.message);
    }
  } else {
    console.log('✓ Rozblog target of 1,000 articles already achieved!');
  }

  // 4. Blogfa Batch
  if (status.blogfa_published < 1000) {
    console.log(`\n--- [Blogfa] Fetching next batch of ${batchSize} articles ---`);
    try {
      const blogfaArticles = await fetchSupabaseArticles(BLOGFA_BLOG_ID, status.blogfa_published, batchSize);
      console.log(`Fetched ${blogfaArticles.length} articles from Supabase.`);

      let blogfaSuccessCount = 0;
      for (let i = 0; i < blogfaArticles.length; i++) {
        const ok = publishBlogfaArticle(blogfaArticles[i], i, status.blogfa_published);
        if (ok) {
          status.blogfa_published += 1;
          blogfaSuccessCount++;
          console.log(`✓ [Blogfa] (${status.blogfa_published}/1000) ${blogfaArticles[i].title.substring(0, 50)}...`);
        } else {
          console.log(`✗ [Blogfa] Failed: ${blogfaArticles[i].title.substring(0, 50)}...`);
        }
        await new Promise(r => setTimeout(r, 1200));
      }
      console.log(`Blogfa batch complete: +${blogfaSuccessCount} published.`);

      // Regenerate Blogfa cache
      try {
        execSync(`${CURL} -s -b "${BLOGFA_COOKIES}" -c "${BLOGFA_COOKIES}" --max-time 15 "https://blogfa.com/desktop/refreshblog.ashx?r=${Date.now()}"`, { timeout: 20000 });
        console.log('✓ Blogfa static cache refreshed.');
      } catch (e) {}
    } catch (err) {
      console.error('Error in Blogfa cycle:', err.message);
    }
  } else {
    console.log('✓ Blogfa target of 1,000 articles already achieved!');
  }

  status.last_updated = new Date().toISOString();
  saveStatus(status);

  console.log(`\n======================================================`);
  console.log(`🏁 Cycle Complete. Updated Status:`);
  console.log(JSON.stringify(status, null, 2));
  console.log(`======================================================\n`);
}

if (require.main === module) {
  const batch = parseInt(process.argv[2], 10) || 15;
  runPublisherCycle(batch).catch(err => {
    console.error('Fatal Publisher Error:', err);
    process.exit(1);
  });
}

module.exports = { runPublisherCycle };
